### ISSUE TITLE
Empty sprite image

### ISSUE THREAD

**Issue by daytonn** [hagenburger/lemonade#30]
Using a clean stand-alone compass project, I added the require "lemonade" line to my config file. I added a few icons inside an images/icons directory (fam fam silk icons) then added the following styles to my src/screen.scss file:

<pre>
.accept {
     background: sprite-image("icons/accept.png");
}

.add {
     background: sprite-image("icons/add.png");
}
</pre>

There were no errors in compass and an icons.png file was generated but it was a blank png the size of the two images. My config is:

<pre>
# Require any additional compass plugins here.
require "lemonade"
# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "stylesheets"
sass_dir = "src"
images_dir = "images"
javascripts_dir = "javascripts"
# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true
</pre>

**Comment by marcdittmann** [comment]
i have exactly the same problem. No Errors, correct CSS but empty .png

**Comment by ukd1** [comment]
I have this problem too - correct css & empty PNG

**Comment by fareesh** [comment]
Same issue. Empty PNG. Was working fine before, then did an update and something went wrong.

EDIT: Removed the new chunky_png gem (1.0.1) and kept only the older version I had installed (0.12.0) and it seems to have fixed the issue.

**Comment by daytonn** [comment]
I can confirm that downgrading from chunky_png 1.0.1 and installing 0.12.0 fixes the issue.

**Comment by ukd1** [comment]
I fixed this problem by doing; gem install compass --pre

**Comment by marcdittmann** [comment]
i also confirm downgrading is the solution.

thanks

**Comment by dirksiemers** [comment]
Still not working :(

compass (0.10.6)
lemonade (0.3.4)
chunky_png (0.12.0)

any ideas?

**Comment by fareesh** [comment]
@dirksiemers, Steps I used were:
- Modify Gemfile
- Remove Gemfile.lock
- Remove .bundle
- bundle install

I'd recommend branching before in case something else breaks :P

**Comment by dirksiemers** [comment]
sorry, not working at all

**Comment by fareesh** [comment]
Hmm.. Are you running compass compile --force right after? Try removing the empty PNGs and see if they are being re-generated.

**Comment by dirksiemers** [comment]
I used "compass compile --force" after I removed the old png and get a new one with the correct size of 5 x 16x16 pngs (16x80) but its blank.
If I remove one png I get a 16x64 png, which size is okay, but it´s also empty :(

**Comment by eleaar** [comment]
I have exactly the same issue that dirksiemers.

When I last compiled my css's, like two weeks ago, everything just worked smooth

**Comment by marcdittmann** [comment]
This fixed it for me:

sudo gem install sass haml  compass staticmatic --pre --no-ri --no-rdoc

**Comment by paulo72** [comment]
Spent the best part of today banging my head on this one, rolling back chunky_png worked. Finally got sorted using the following:

chunky_png (0.12.0)
compass (0.10.6)
lemonade (0.3.4)

not sure if these are relevant, but they are being used:

haml (3.0.25)
rubygems-update (1.3.7)
sass (3.1.0.alpha.252)

**Comment by mkhattab** [comment]
You can solve this problem by entering this into your config.rb:

gem 'chunky_png', '=0.12.0'
require 'lemonade'

This specifically requests the chunky_png version that makes lemonade work again
